# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_auto_20161112_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydarzenie',
            name='e_hour',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='wydarzenie',
            name='s_hour',
            field=models.IntegerField(default=10),
        ),
    ]
